
spring:
  application:
    name: front

chaekmate:
  gateway:
    url: ${GATEWAY_URL:http://localhost:10320}

minio:
  url: ${MINIO_URL:http://storage.java21.net:8000}
  accessKey: ${MINIO_ACCESS_KEY:3P0frMluG9VWCtYH9I7e}
  secretKey: ${MINIO_SECRET_KEY:97xkODbuUyRx6NOAUbQGCuxJdXmfC83UqVKFDFrj}
  bucketName: ${MINIO_BUCKET_NAME:chaekmate-image-server}

server:
  port: ${PORT_NUMBER}
