spring:
  application:
    name: front

chaekmate:
  gateway:
    url: http://localhost:8080

server:
  port: 5173

minio:
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucketName: ${MINIO_BUCKET_NAME}
  chaekmateImageUrl: ${CHAEKMATE_IMAGE_URL}
