name: PR Notify to Dooray

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Dooray
        shell: bash
        env:
          DOORAY_URL: ${{ secrets.DOORAY_URL }}
        run: |
          curl -X POST "$DOORAY_URL" \
            -H "Content-Type: application/json" \
            --data-raw '{
              "botName": "GitHub PR Bot",
              "text": "ğŸš€ ìƒˆë¡œìš´ PRì´ ìƒì„±ë˜ì—ˆìŠµë‹ˆë‹¤!\nì œëª©: test3\nì‘ì„±ì: Charl-es\në§í¬: https://github.com/nhnacademy-be11-1/chaekmate-front/pull/3"
            }'
